// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package modelv2

type Query struct {
}

type SpecRun struct {
	ID              int    `json:"id"`
	SuiteID         int    `json:"suiteId"`
	SpecDescription string `json:"specDescription"`
	Status          string `json:"status"`
	Message         string `json:"message"`
	StartTime       string `json:"startTime"`
	EndTime         string `json:"endTime"`
	Tags            []*Tag `json:"tags"`
}

type SuiteRun struct {
	ID        int        `json:"id"`
	TestRunID int        `json:"testRunId"`
	SuiteName string     `json:"suiteName"`
	StartTime string     `json:"startTime"`
	EndTime   string     `json:"endTime"`
	SpecRuns  []*SpecRun `json:"specRuns"`
}

type Tag struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type TestRun struct {
	ID              int    `json:"id"`
	TestProjectName string `json:"testProjectName"`
	TestSeed        int    `json:"testSeed"`
	StartTime       string `json:"startTime"`
	EndTime         string `json:"endTime"`
	//SuiteRuns       []*SuiteRun `json:"suiteRuns"`
}

type TestRunFilter struct {
	ID              int    `json:"id"`
	TestProjectName string `json:"testProjectName"`
}
